{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "e7b9ffcb-3b89-4575-848f-b18d0e66093b",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''Module 4: Individual Programming Assignment 1\n",
    "\n",
    "Parsing Data\n",
    "\n",
    "This assignment covers your ability to manipulate data in Python.\n",
    "'''\n",
    "\n",
    "def relationship_status(from_member, to_member, social_graph):\n",
    "    '''Relationship Status.\n",
    "    20 points.\n",
    "\n",
    "    Let us pretend that you are building a new app.\n",
    "    Your app supports social media functionality, which means that users can have\n",
    "    relationships with other users.\n",
    "\n",
    "    There are two guidelines for describing relationships on this social media app:\n",
    "    1. Any user can follow any other user.\n",
    "    2. If two users follow each other, they are considered friends.\n",
    "\n",
    "    This function describes the relationship that two users have with each other.\n",
    "\n",
    "    Please see \"assignment-4-sample-data.py\" for sample data. The social graph\n",
    "    will adhere to the same pattern.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    from_member: str\n",
    "        the subject member\n",
    "    to_member: str\n",
    "        the object member\n",
    "    social_graph: dict\n",
    "        the relationship data    \n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        \"follower\" if fromMember follows toMember,\n",
    "        \"followed by\" if fromMember is followed by toMember,\n",
    "        \"friends\" if fromMember and toMember follow each other,\n",
    "        \"no relationship\" if neither fromMember nor toMember follow each other.\n",
    "    '''\n",
    "    # Replace `pass` with your code. \n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    \n",
    "    #Check the people followed by from_member\n",
    "    from_member_following = social_graph[from_member]['following']\n",
    "    \n",
    "    #Check the people followed by toMember\n",
    "    to_member_following = social_graph[to_member]['following']\n",
    "\n",
    "    #Check if the user is in the list of the 'following' of the other user (and vice versa)\n",
    "    fromMember_follows_toMember = to_member in from_member_following\n",
    "    toMember_follows_fromMember = from_member in to_member_following\n",
    "    \n",
    "    result = ''\n",
    "    \n",
    "    if fromMember_follows_toMember and toMember_follows_fromMember:\n",
    "        result = 'friends'\n",
    "    elif fromMember_follows_toMember and not toMember_follows_fromMember:\n",
    "        result = 'follower'\n",
    "    elif not fromMember_follows_toMember and toMember_follows_fromMember:\n",
    "        result = 'followed by'\n",
    "    else:\n",
    "        result = 'no relationship'\n",
    "    \n",
    "    return result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "14cef110-f2b8-41ed-9de6-77031c3854e3",
   "metadata": {},
   "outputs": [],
   "source": [
    "def tic_tac_toe(board):\n",
    "    '''Tic Tac Toe. \n",
    "    25 points.\n",
    "\n",
    "    Tic Tac Toe is a common paper-and-pencil game. \n",
    "    Players must attempt to successfully draw a straight line of their symbol across a grid.\n",
    "    The player that does this first is considered the winner.\n",
    "\n",
    "    This function evaluates a tic tac toe board and returns the winner.\n",
    "\n",
    "    Please see \"assignment-4-sample-data.py\" for sample data. The board will adhere\n",
    "    to the same pattern. The board may by 3x3, 4x4, 5x5, or 6x6. The board will never\n",
    "    have more than one winner. The board will only ever have 2 unique symbols at the same time.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    board: list\n",
    "        the representation of the tic-tac-toe board as a square list of lists\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the symbol of the winner or \"NO WINNER\" if there is no winner\n",
    "    '''\n",
    "    # Replace `pass` with your code. \n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    \n",
    "    #Check every row in the board\n",
    "    for row in board: \n",
    "        #Check if all the symbols in the row are the same\n",
    "        is_same = all([row[0] ==symbol for symbol in row])\n",
    "        if is_same:\n",
    "            return row [0] \n",
    "    \n",
    "    #Check every column in the board\n",
    "    for column in zip(*board):\n",
    "        #Check if all the symbols in the column are the same\n",
    "        is_same = all([column[0] ==symbol for symbol in column])\n",
    "        if is_same:\n",
    "            return column [0]\n",
    "    \n",
    "    #n x n board\n",
    "    n = len(board)\n",
    "    \n",
    "    #Check the up-down main diagonal\n",
    "    up_down_symbols = [board[i][i] for i in range(n)]\n",
    "    up_down_same = all([up_down_symbols[0] ==symbol for symbol in up_down_symbols])\n",
    "    if up_down_same:\n",
    "        return up_down_symbols[0]\n",
    "    \n",
    "    #Check the down-up main diagonal\n",
    "    down_up_symbols = [board[i][i] for i in range(n)]\n",
    "    down_up_same = all([down_up_same[0] ==symbol for symbol in down_up_same])\n",
    "    if down_up_same:\n",
    "        return down_up_symbols[0]\n",
    "\n",
    "    #If no uniform symbols can be found across rows, columns, main diagonals, simply return 'NO WINNER'\n",
    "    return 'NO WINNER'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "9851d2c0-22c4-4fde-95f4-ab01c8506b66",
   "metadata": {},
   "outputs": [],
   "source": [
    "def eta(first_stop, second_stop, route_map):\n",
    "    '''ETA. \n",
    "    25 points.\n",
    "\n",
    "    A shuttle van service is tasked to travel along a predefined circlar route.\n",
    "    This route is divided into several legs between stops.\n",
    "    The route is one-way only, and it is fully connected to itself.\n",
    "\n",
    "    This function returns how long it will take the shuttle to arrive at a stop\n",
    "    after leaving another stop.\n",
    "\n",
    "    Please see \"mod-4-ipa-1-sample-data.py\" for sample data. The route map will\n",
    "    adhere to the same pattern. The route map may contain more legs and more stops,\n",
    "    but it will always be one-way and fully enclosed.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    first_stop: str\n",
    "        the stop that the shuttle will leave\n",
    "    second_stop: str\n",
    "        the stop that the shuttle will arrive at\n",
    "    route_map: dict\n",
    "        the data describing the routes\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    int\n",
    "        the time it will take the shuttle to travel from first_stop to second_stop\n",
    "    '''\n",
    "    # Replace `pass` with your code. \n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    \n",
    "    tuple_key = (first_stop, second_stop)\n",
    "    travel_time = legs[tuple_key]\n",
    "    \n",
    "    return travel_time"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
